### ISSUE TITLE
Missing Dockerfile/.env

### ISSUE THREAD

**Issue by nolantait** [fremantle-industries/prop#137]
Awesome work! Wanted to build something just like this. You're a gem.

I'm struggling to get it running with docker-compose alone. Any suggestions?

I'm getting a compiling error on rust right now: `Can't compile ex_keccak`.

No rush, understand you're busy. Keep up the great stuff

**Comment by rupurt** [comment]
Hey @nolantait,

You need to have rust installed for `ex_keccak`. I'll update the README with some improved instructions. 

I've also got a bit of maintenance I need to do on prop to upgrade it to the latest phoenix + live view.

**Comment by rupurt** [comment]
https://github.com/fremantle-industries/prop#requirements

**Comment by rupurt** [comment]
I've pushed my WIP branch for running `prop` within `docker-compose`. There's a bunch of rough edges outlined in the PR that I should be able to resolve in the next few weeks.

https://github.com/fremantle-industries/prop/pull/138

**Comment by nolantait** [comment]
Thanks so much for the quick response.

With your PR and some debugging I got a working version going.

I wrote about my experience for you here: https://www.notion.so/taitventures/Prop-User-Experience-Log-31c7daa29a8d471b86c015359e8b4e94

Looking forward to playing around and seeing how I might help contribute

**Comment by rupurt** [comment]
> Thanks so much for the quick response.

No worries. Always exciting when someone new comes along that wants to use the tooling :smile: 

> With your PR and some debugging I got a running version going. Still a lot of errors I'm working through.

:partying_face: 

> I'll be writing about my experience for you here: https://www.notion.so/taitventures/Prop-User-Experience-Log-31c7daa29a8d471b86c015359e8b4e94

Thanks for the notes. I've added some [extra documentation](https://github.com/fremantle-industries/prop/tree/bump-phoenix-1.6#install) to the README. Lmk if it doesn't cover all your pain points.

There's a few points in the doc that I'll expand on:

> Added grafana dependency to reverse_proxy to prevent it complaining that grafana server is missing on startup

I've specifically decided not to specify the dependent services in `docker-compose.yml` so that I start subsets of services. e.g. `$ docker-compose db web reverse_proxy` where I don't want `grafana` or `prometheus` to be started. If there's another command to achieve the same result I'm happy to update the compose file.

> Grafana doesn't like empty file directors for plugins and notifiers

It should still work AFAIK, I just haven't required any plugins so far and copied over a previous projects config. I'll look into fixing the log messages

> Looking forward to playing around and seeing how I might help contribute, maybe I can help write the docker installation instructions?

Any help is always appreciated :+1: :100: Documentation is on the light side because it's always a trade off between building that next feature and I'm a bit lazy... :grin: 

I was a ruby programmer in the past so hopefully you like Elixir. It's a little bit different, but shares much of the same philosophy around developer productiveness, comprehension, community etc...

**Comment by rupurt** [comment]
@nolantait is this still an open issue for you?

**Comment by nolantait** [comment]
Nope, the .env.example and the improved README fixes all these issues.
